---
- name: Copy su log to /tmp and compress (Ubuntu 22/24 & RHEL/CentOS)
  hosts: all
  gather_facts: true

  vars:
    tmp_dir: /tmp

  tasks:
    - name: Detect distro family
      ansible.builtin.set_fact:
        is_ubuntu: "{{ (ansible_facts.distribution | lower) == 'ubuntu' }}"

    - name: Build candidate su/auth log list (ordered)
      ansible.builtin.set_fact:
        su_candidates: >-
          {{ (is_ubuntu | ternary(
                ['/var/log/auth.log'],
                ['/var/log/secure', '/var/log/sulog', '/var/log/messages', '/var/log/auth.log']
              )) }}

    - name: Stat candidate logs
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ su_candidates }}"
      register: su_stats

    - name: Pick first existing log
      ansible.builtin.set_fact:
        su_log_found: "{{ (su_stats.results | selectattr('stat.exists') | map(attribute='stat.path') | list | first) | default(omit) }}"

    - name: Fail if no suitable su/auth log found
      ansible.builtin.fail:
        msg: "No su/auth log found. Checked: {{ su_candidates }}"
      when: su_log_found is not defined

    - name: Ensure /tmp exists with sane perms
      ansible.builtin.file:
        path: "{{ tmp_dir }}"
        state: directory
        mode: "1777"

    - name: Copy su/auth log into /tmp
      ansible.builtin.copy:
        src: "{{ su_log_found }}"
        dest: "{{ tmp_dir }}/{{ su_log_found | basename }}"
        remote_src: true
        mode: "0640"

    - name: Create tar.gz archive in /tmp
      community.general.archive:
        path: "{{ tmp_dir }}/{{ su_log_found | basename }}"
        dest: "{{ tmp_dir }}/{{ su_log_found | basename }}.tar.gz"
        format: gz
        remove: false

    - name: Report archive path
      ansible.builtin.debug:
        msg:
          source_log: "{{ su_log_found }}"
          archive: "{{ tmp_dir }}/{{ su_log_found | basename }}.tar.gz"
