---
- name: Filesystem report and largest files under /home
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    home_path: /home
    top_n: 20

  tasks:
    - name: Collect filesystem usage (df -hT) excluding tmpfs/devtmpfs/etc.
      ansible.builtin.shell: |
        df -h 
      args:
        executable: /bin/bash
      register: df_out
      changed_when: false

    - name: Collect block devices info (lsblk -f)
      ansible.builtin.command: lsblk -f -o NAME,FSTYPE,SIZE,FSUSE%,MOUNTPOINT,UUID
      register: lsblk_out
      changed_when: false

    - name: Check if {{ home_path }} exists
      ansible.builtin.stat:
        path: "{{ home_path }}"
      register: st_home

    # - name: Write consolidated report to /tmp
    #   ansible.builtin.copy:
    #     dest: "/tmp/fs_report_{{ inventory_hostname }}.txt"
    #     mode: "0644"
    #     content: |
    #       Host: {{ inventory_hostname }}
    #       Date: {{ ansible_date_time.date }} {{ ansible_date_time.time }}

    #       === Filesystems (df -hT, filtered) ===
    #       {{ df_out.stdout }}

    #       === Block Devices (lsblk -f) ===
    #       {{ lsblk_out.stdout }}

    #       === Largest {{ top_n }} files under {{ home_path }} (bytes \t path) ===
    #       {{ largest_out.stdout }}

    # - name: Show where the report was saved
    #   ansible.builtin.debug:
    #     msg:
    #       - "Report saved to /tmp/fs_report_{{ inventory_hostname }}.txt"
    #       - "Top {{ top_n }} largest files under {{ home_path }} gathered."

    # OPTIONAL: fetch the report back to the control node
    # - name: Fetch report to control node
    #   ansible.builtin.fetch:
    #     src: "/tmp/fs_report_{{ inventory_hostname }}.txt"
    #     dest: "./fs_reports/"
    #     flat: yes
