---
- hosts: all
  gather_facts: true
  tasks:
    - name: Retrieve hostname using Ansible facts
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Retrieve current date and time using Ansible facts
      debug:
        msg: "Date and Time: {{ ansible_date_time.date }} {{ ansible_date_time.time }}"
