---
- name: Send test syslog message via logger
  hosts: all
  become: true
  gather_facts: true

  vars:
    syslog_tag: "TEST01132026KATTIA"
    syslog_message: "hello from {{ inventory_hostname }} via UDP"

  tasks:

    - name: Send test message with logger demo with Kattia
      ansible.builtin.command: >
        logger -t {{ syslog_tag }} "{{ syslog_message }}"
      register: logger_output
      changed_when: false  # logger doesn't change system state

    - name: Show stdout/stderr from logger
      ansible.builtin.debug:
        var: logger_output
