---
ansible_user: freddygonzalez
ansible_become: true
ansible_become_method: sudo

ansible_password: "{{ vault_freddygonzalez_password }}"
ansible_become_password: "{{ vault_freddygonzalez_password }}"
