# =============================================================================
# Lab Infrastructure Ansible Inventory
# =============================================================================

[lab_infra_servers]
lab-ubuntu-2404-monitoring         ansible_host=192.168.1.153
lab-ubuntu-2404-boltdiy            ansible_host=192.168.1.170
lab-ubuntu-logger                  ansible_host=192.168.1.138
lab-ubuntu-2204-jenkins            ansible_host=192.168.1.190
lab-ubuntu-2404-n8n                ansible_host=192.168.1.76
lab-centos8-kickstart              ansible_host=192.168.1.75
; lab-ubuntu-2204-ns1                ansible_host=192.168.1.185
lab-rhel9-app-atomiclabs           ansible_host=192.168.1.148
lab-ubuntu-2404-awx-secondary      ansible_host=192.168.1.140
lab-rhel9-aap-tower-5004-232      ansible_host=192.168.1.232


[lab_centos_7]
lab-centos7-aap-client-920-145     ansible_host=192.168.1.145
lab-centos7-aap-client-921-123     ansible_host=192.168.1.123
lab-centos7-aap-client-922-80      ansible_host=192.168.1.80
lab-centos7-aap-client-923-243     ansible_host=192.168.1.243
lab-centos7-aap-client-924-117     ansible_host=192.168.1.117
lab-centos7-aap-client-925-108     ansible_host=192.168.1.108


[lab_rhel_9]
lab-rhel9-aap-client-941-83        ansible_host=192.168.1.83
lab-rhel9-aap-client-942-231       ansible_host=192.168.1.231
lab-rhel9-aap-client-943-139       ansible_host=192.168.1.139
lab-rhel9-aap-client-944-224       ansible_host=192.168.1.224
lab-rhel9-aap-client-945-107       ansible_host=192.168.1.107


[lab_centos_8]
lab-centos8-aap-client-990-101     ansible_host=192.168.1.101
lab-centos8-aap-client-991-152     ansible_host=192.168.1.152
lab-centos8-aap-client-992-144     ansible_host=192.168.1.144
lab-centos8-aap-client-993-119     ansible_host=192.168.1.119
lab-centos8-aap-client-994-181     ansible_host=192.168.1.181
lab-centos8-aap-client-995-111     ansible_host=192.168.1.111


[lab_ubuntu_24]
lab-ubuntu24-aap-client-960-178    ansible_host=192.168.1.178
lab-ubuntu24-aap-sfs-965-141       ansible_host=192.168.1.141
lab-ubuntu24-aap-client-964-114    ansible_host=192.168.1.114
lab-ubuntu24-aap-client-963-142    ansible_host=192.168.1.142
lab-ubuntu24-aap-client-962-229    ansible_host=192.168.1.229
lab-ubuntu24-aap-client-961-183    ansible_host=192.168.1.183
lab-ubuntu-2404-coderepo-903-125   ansible_host=192.168.1.125

[lab_opensuse_15]
lab-suse15-aap-client-970-223      ansible_host=192.168.1.223
lab-opensuse-aap-client-2011-130   ansible_host=192.168.1.130
lab-opensuse-aap-client-2020-234   ansible_host=192.168.1.234


[lab_development_servers]
lab-ubuntu2404-opencode-704-197        ansible_host=192.168.1.197
; lab-ubuntu2404-aap-client-rust-8003-185 ansible_host=192.168.1.185
lab-rhel9-aap-tower-5004-232           ansible_host=192.168.1.232
lab-centos7-0900-awxprimary-801-225    ansible_host=192.168.1.225


[lab_dns_servers]
lab-ubuntu2404-dns-client-8004-164     ansible_host=192.168.1.164
lab-ubuntu2404-dns-resolver-8006-196   ansible_host=192.168.1.196
lab-ubuntu2404-dns-ha1-8007-239        ansible_host=192.168.1.239
lab-ubuntu2404-dns-ha2-8008-103        ansible_host=192.168.1.103


# =============================================================================
# Aggregate Wazuh Agent Group
# =============================================================================

[wazuh_agents:children]
lab_infra_servers
lab_centos_7
lab_rhel_9
lab_centos_8
lab_ubuntu_24
lab_opensuse_15
lab_development_servers
lab_dns_servers


; [wazuh_agents:vars]
; ansible_user=freddygonzalez